### ISSUE TITLE
Dependabot - Clean Setup

### ISSUE THREAD

**Issue by jonathangoulding** [DEFRA/water-abstraction-team#12]
https://eaflood.atlassian.net/browse/WATER-3661

Start fresh with the Dependabot branches. 

- delete all Dependabot branches 
- ensure Dependabot works with current pipeline almost (all repos do not run pipelines on '!dependabot/**' blame @jonathangoulding )

**Comment by Cruikshanks** [comment]
Expanding this slightly, when we drop `.github)/dependabot.yml` into the repo (if it doesn't exist) it should include github-actions as a thing its checking and updating.

Here is an example from [sroc-charging-module](https://github.com/DEFRA/sroc-charging-module-api/blob/main/.github/dependabot.yml)

```yaml
# See the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
- package-ecosystem: "github-actions"
  # Workflow files stored in the default location of `.github/workflows`
  directory: "/"
  schedule:
    interval: "daily"
```
