### ISSUE TITLE
Replace deprecated set-output cmd in GitHub CI workflows

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#56]
We've updated all our repos to use a standard GitHub CI Workflow template. In that template is the following step which reads the Node version from an `.nvmrc` file and sets it as the output for use in a later step

```yaml
      # Our projects use .nvmrc files to specify the node version to use. We can read and then output it as the result
      # this step. Subsequent steps can then access the value
      - name: Read Node version
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        # Give the step an ID to make it easier to refer to
        id: nvm
```

We're now seeing this warning message in when the CI build task runs

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

It's actually only a minor change. Using https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files as a guide we can continue to do what we're doing. We just need to save the Node version into an environment variable and then read it in the subsequent step. But we will need to do it in every repo 😬

- [x] hapi-pg-rest-api
- [x] water-abstraction-helpers
- [x] water-abstraction-import
- [x] water-abstraction-permit-repository
- [x] water-abstraction-reporting
- [x] water-abstraction-returns
- [x] water-abstraction-service
- [x] water-abstraction-tactical-crm
- [x] water-abstraction-tactical-idm
- [x] water-abstraction-ui
